-- Migration script for Foreign Key Cascade Delete on Posts
-- Run this if your MySQL database foreign keys were created without ON DELETE CASCADE

-- 1. Comments table: Cascade delete when referenced post is deleted
-- Note: Replace fk constraint name if auto-generated by Hibernate/MySQL
ALTER TABLE comments ADD CONSTRAINT fk_comments_post_cascade 
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;

-- 2. Likes table: Cascade delete when referenced post is deleted
ALTER TABLE likes ADD CONSTRAINT fk_likes_post_cascade 
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE;

-- 3. Reports table: Cascade delete when reported post or reported community post is deleted
ALTER TABLE reports ADD CONSTRAINT fk_reports_reported_post_cascade 
    FOREIGN KEY (reported_post_id) REFERENCES posts(id) ON DELETE CASCADE;

ALTER TABLE reports ADD CONSTRAINT fk_reports_reported_community_post_cascade 
    FOREIGN KEY (reported_community_post_id) REFERENCES community_posts(id) ON DELETE CASCADE;
